get '/blogs', to: 'blogs#index'
get '/blogs/:id', to: 'blogs#show'
get '/blogs/new', to: 'blogs#new'
post '/blogs', to: 'blogs#create'
patch '/blogs/:id', to: 'blogs#update'
delete '/blogs/:id', to: 'blogs#destroy'
